@echo off
:: =============================================================================
::  NexusMind — Easy Installer for Windows
::  Usage: Double-click install.bat  OR  run from Command Prompt / PowerShell
:: =============================================================================
setlocal EnableDelayedExpansion
title NexusMind Installer

echo.
echo   ########################################################
echo   #                                                      #
echo   #          NexusMind - AI Knowledge Platform          #
echo   #            Easy Installer for Windows               #
echo   #                                                      #
echo   ########################################################
echo.

set "REPO_DIR=%~dp0"
set "REPO_DIR=%REPO_DIR:~0,-1%"
set "ENV_FILE=%REPO_DIR%\backend\.env"

:: ─── Step 1: Check Python ────────────────────────────────────────────────────
echo [INFO] Checking Python...
python --version >nul 2>&1
if errorlevel 1 (
  python3 --version >nul 2>&1
  if errorlevel 1 (
    echo [ERROR] Python 3.9+ is required.
    echo         Download from: https://python.org/downloads/
    pause
    exit /b 1
  )
  set "PYTHON=python3"
) else (
  set "PYTHON=python"
)
%PYTHON% --version
echo.

:: ─── Step 2: Check Node.js ───────────────────────────────────────────────────
echo [INFO] Checking Node.js...
node --version >nul 2>&1
if errorlevel 1 (
  echo [ERROR] Node.js 16+ is required.
  echo         Download from: https://nodejs.org/
  pause
  exit /b 1
)
node --version
npm --version
echo.

:: ─── Step 3: Install method ──────────────────────────────────────────────────
echo How do you want to run NexusMind?
echo   1) Local  (Python + Node.js)  - Recommended
echo   2) Docker Compose             - For production / always-on use
echo.
set /p INSTALL_METHOD=Choice [1/2] (default: 1): 
if "%INSTALL_METHOD%"=="" set "INSTALL_METHOD=1"
echo.

if "%INSTALL_METHOD%"=="2" (
  docker --version >nul 2>&1
  if errorlevel 1 (
    echo [ERROR] Docker is required for Docker mode.
    echo         Download from: https://docker.com/
    pause
    exit /b 1
  )
)

:: ─── Step 4: Configure AI providers ─────────────────────────────────────────
echo Configure AI providers (press Enter to skip):
echo.
set /p OLLAMA_URL=  Ollama URL (default: http://localhost:11434): 
if "%OLLAMA_URL%"=="" set "OLLAMA_URL=http://localhost:11434"

set /p OPENAI_KEY=  OpenAI API key (sk-...): 
set /p ANTHROPIC_KEY=  Anthropic API key (sk-ant-...): 
set /p GOOGLE_KEY=  Google Gemini API key (AIza...): 

echo.
echo [INFO] Writing backend\.env ...

(
  echo # NexusMind Configuration — generated by install.bat
  echo.
  echo # ── App ─────────────────────────────────────────────
  echo SECRET_KEY=nexusmind-secret-change-in-production
  echo DEBUG=false
  echo.
  echo # ── AI Providers ────────────────────────────────────
  echo OLLAMA_BASE_URL=%OLLAMA_URL%
  echo OLLAMA_DEFAULT_MODEL=llama3
) > "%ENV_FILE%"

if not "%OPENAI_KEY%"==""    echo OPENAI_API_KEY=%OPENAI_KEY%       >> "%ENV_FILE%"
if not "%ANTHROPIC_KEY%"=="" echo ANTHROPIC_API_KEY=%ANTHROPIC_KEY% >> "%ENV_FILE%"
if not "%GOOGLE_KEY%"==""    echo GOOGLE_API_KEY=%GOOGLE_KEY%       >> "%ENV_FILE%"

(
  echo.
  echo # ── Database ─────────────────────────────────────────
  echo DATABASE_URL=sqlite:///./data/nexusmind.db
  echo.
  echo # ── RAG / Embeddings ─────────────────────────────────
  echo CHROMA_DB_PATH=./data/chroma_db
  echo EMBEDDING_MODEL=all-MiniLM-L6-v2
  echo RAG_CHUNK_SIZE=512
  echo RAG_TOP_K=5
) >> "%ENV_FILE%"

echo [OK] .env created
echo.

:: ─── Step 5: Install dependencies ────────────────────────────────────────────
if "%INSTALL_METHOD%"=="1" (
  echo [INFO] Setting up Python virtual environment...
  cd /d "%REPO_DIR%\backend"

  if not exist "venv\" (
    %PYTHON% -m venv venv
    echo [OK] Virtual environment created
  ) else (
    echo [INFO] Virtual environment already exists
  )

  call venv\Scripts\activate.bat
  if errorlevel 1 (
    echo [ERROR] Could not activate virtual environment
    pause
    exit /b 1
  )
  echo [OK] Virtual environment activated

  echo [INFO] Installing Python dependencies (may take a few minutes)...
  pip install --upgrade pip -q
  pip install -r requirements.txt -q
  if errorlevel 1 (
    echo [ERROR] Failed to install Python dependencies
    pause
    exit /b 1
  )
  echo [OK] Python dependencies installed

  cd /d "%REPO_DIR%\frontend"
  echo [INFO] Installing frontend dependencies...
  npm install --legacy-peer-deps -q
  if errorlevel 1 (
    echo [ERROR] Failed to install frontend dependencies
    pause
    exit /b 1
  )
  echo [OK] Frontend dependencies installed

  cd /d "%REPO_DIR%"
  if not exist "backend\data\" mkdir backend\data
  if not exist "backend\extensions\installed\" mkdir backend\extensions\installed

  echo.
  echo   ########################################################
  echo   #              Installation Complete!                  #
  echo   ########################################################
  echo.
  echo   To start NexusMind, run:
  echo     start-dev.bat
  echo.
  echo   Or manually open two terminals:
  echo     Terminal 1: cd backend ^&^& venv\Scripts\activate ^&^& uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  echo     Terminal 2: cd frontend ^&^& npm run dev
  echo.
  echo   URLs:
  echo     Frontend:  http://localhost:3000
  echo     Backend:   http://localhost:8000
  echo     API docs:  http://localhost:8000/docs
  echo.

  set /p START_NOW=Start NexusMind now? [y/N]: 
  if /i "!START_NOW!"=="y" (
    cd /d "%REPO_DIR%"
    if exist "start-dev.bat" (
      call start-dev.bat
    ) else (
      :: Launch both in separate windows
      start "NexusMind Backend" cmd /k "cd /d "%REPO_DIR%\backend" && call venv\Scripts\activate && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
      timeout /t 3 >nul
      start "NexusMind Frontend" cmd /k "cd /d "%REPO_DIR%\frontend" && npm run dev"
      echo.
      echo [OK] NexusMind is starting in separate windows.
      echo      Open http://localhost:3000 in your browser.
    )
  )

) else (
  :: Docker Compose
  cd /d "%REPO_DIR%"
  copy /y "%ENV_FILE%" ".env" >nul 2>&1

  echo [INFO] Building Docker images (may take a few minutes)...
  docker compose up --build -d
  if errorlevel 1 (
    docker-compose up --build -d
    if errorlevel 1 (
      echo [ERROR] Docker Compose failed. Check Docker is running.
      pause
      exit /b 1
    )
  )

  echo.
  echo   ########################################################
  echo   #    NexusMind is running via Docker!                  #
  echo   ########################################################
  echo.
  echo   URLs:
  echo     Frontend:  http://localhost:3000
  echo     Backend:   http://localhost:8000
  echo     API docs:  http://localhost:8000/docs
  echo.
  echo   Manage:
  echo     Stop:    docker compose down
  echo     Logs:    docker compose logs -f
  echo     Restart: docker compose restart
  echo.
)

pause
endlocal
