#!/bin/bash
# =============================================================================
#  NexusMind — Easy Installer for Linux & macOS
#  Usage: bash install.sh
# =============================================================================

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }
ask()     { echo -e "${BOLD}$*${NC}"; }

echo ""
echo -e "${BOLD}${CYAN}"
echo "  ███╗   ██╗███████╗██╗  ██╗██╗   ██╗███████╗███╗   ███╗██╗███╗   ██╗██████╗ "
echo "  ████╗  ██║██╔════╝╚██╗██╔╝██║   ██║██╔════╝████╗ ████║██║████╗  ██║██╔══██╗"
echo "  ██╔██╗ ██║█████╗   ╚███╔╝ ██║   ██║███████╗██╔████╔██║██║██╔██╗ ██║██║  ██║"
echo "  ██║╚██╗██║██╔══╝   ██╔██╗ ██║   ██║╚════██║██║╚██╔╝██║██║██║╚██╗██║██║  ██║"
echo "  ██║ ╚████║███████╗██╔╝ ██╗╚██████╔╝███████║██║ ╚═╝ ██║██║██║ ╚████║██████╔╝"
echo "  ╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚═╝     ╚═╝╚═╝╚═╝  ╚═══╝╚═════╝ "
echo -e "${NC}"
echo -e "  ${BOLD}AI-Powered Knowledge Management Platform${NC}"
echo ""

# ─── Step 1: Detect OS ────────────────────────────────────────────────────────
OS="$(uname -s)"
case "$OS" in
  Linux*)  PLATFORM="Linux" ;;
  Darwin*) PLATFORM="macOS" ;;
  *)       error "Unsupported platform: $OS. Use install.bat on Windows." ;;
esac
info "Platform: $PLATFORM"

# ─── Step 2: Check required tools ────────────────────────────────────────────
info "Checking prerequisites…"

# Python
PYTHON=""
for cmd in python3 python; do
  if command -v "$cmd" &>/dev/null; then
    VER=$("$cmd" --version 2>&1 | grep -oP '\d+\.\d+' | head -1)
    MAJOR=$(echo "$VER" | cut -d. -f1)
    MINOR=$(echo "$VER" | cut -d. -f2)
    if [ "$MAJOR" -ge 3 ] && [ "$MINOR" -ge 9 ]; then
      PYTHON="$cmd"
      break
    fi
  fi
done
[ -z "$PYTHON" ] && error "Python 3.9+ is required. Install from https://python.org"
success "Python: $($PYTHON --version)"

# Node.js
if ! command -v node &>/dev/null; then
  error "Node.js 18+ is required. Install from https://nodejs.org"
fi
NODE_VER=$(node --version | grep -oP '\d+' | head -1)
[ "$NODE_VER" -lt 16 ] && error "Node.js 16+ required (found $(node --version))"
success "Node.js: $(node --version)"

# npm
command -v npm &>/dev/null || error "npm is required (comes with Node.js)"
success "npm: $(npm --version)"

# ─── Step 3: Choose install method ───────────────────────────────────────────
echo ""
ask "How do you want to run NexusMind?"
echo "  1) Local (Python + Node.js)  — Recommended for development"
echo "  2) Docker Compose            — Recommended for production"
echo ""
read -rp "Choice [1/2] (default: 1): " INSTALL_METHOD
INSTALL_METHOD="${INSTALL_METHOD:-1}"

if [ "$INSTALL_METHOD" = "2" ]; then
  command -v docker &>/dev/null || error "Docker is required. Install from https://docker.com"
  command -v docker-compose &>/dev/null || (command -v docker &>/dev/null && docker compose version &>/dev/null) || \
    error "docker-compose is required. Install from https://docs.docker.com/compose/"
  success "Docker: $(docker --version)"
fi

# ─── Step 4: Configure AI providers ──────────────────────────────────────────
echo ""
ask "Configure AI providers (press Enter to skip any):"
echo ""

ENV_FILE="$REPO_DIR/backend/.env"

read -rp "  Ollama URL (default: http://localhost:11434): " OLLAMA_URL
OLLAMA_URL="${OLLAMA_URL:-http://localhost:11434}"

read -rp "  OpenAI API key (sk-...): " OPENAI_KEY
read -rp "  Anthropic API key (sk-ant-...): " ANTHROPIC_KEY
read -rp "  Google Gemini API key (AIza...): " GOOGLE_KEY

echo ""
info "Writing configuration to backend/.env …"

cat > "$ENV_FILE" <<EOF
# NexusMind Configuration — generated by install.sh
# Edit this file to update your settings

# ── App ─────────────────────────────────────────────
SECRET_KEY=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 32 2>/dev/null || echo "CHANGE_ME_BEFORE_PRODUCTION")
DEBUG=false
# ⚠ IMPORTANT: Change SECRET_KEY above if the random generation failed

# ── AI Providers ────────────────────────────────────
OLLAMA_BASE_URL=$OLLAMA_URL
OLLAMA_DEFAULT_MODEL=llama3

EOF

[ -n "$OPENAI_KEY" ]     && echo "OPENAI_API_KEY=$OPENAI_KEY"     >> "$ENV_FILE"
[ -n "$ANTHROPIC_KEY" ]  && echo "ANTHROPIC_API_KEY=$ANTHROPIC_KEY"  >> "$ENV_FILE"
[ -n "$GOOGLE_KEY" ]     && echo "GOOGLE_API_KEY=$GOOGLE_KEY"      >> "$ENV_FILE"

cat >> "$ENV_FILE" <<'EOF'

# ── Database ─────────────────────────────────────────
DATABASE_URL=sqlite:///./data/nexusmind.db

# ── RAG / Embeddings ─────────────────────────────────
CHROMA_DB_PATH=./data/chroma_db
EMBEDDING_MODEL=all-MiniLM-L6-v2
RAG_CHUNK_SIZE=512
RAG_TOP_K=5
EOF

success ".env file created at backend/.env"

# ─── Step 5: Install dependencies ────────────────────────────────────────────
echo ""

if [ "$INSTALL_METHOD" = "1" ]; then
  info "Setting up Python virtual environment…"
  cd "$REPO_DIR/backend"
  if [ ! -d "venv" ]; then
    $PYTHON -m venv venv
    success "Virtual environment created"
  else
    info "Virtual environment already exists"
  fi

  # Activate venv
  # shellcheck disable=SC1091
  source venv/bin/activate 2>/dev/null || source venv/Scripts/activate 2>/dev/null || \
    error "Could not activate virtual environment"
  success "Virtual environment activated"

  info "Installing Python dependencies (this may take a few minutes)…"
  pip install --upgrade pip -q
  pip install -r requirements.txt -q
  success "Python dependencies installed"

  cd "$REPO_DIR"
  info "Installing frontend dependencies…"
  cd frontend
  npm install --legacy-peer-deps -q
  success "Frontend dependencies installed"
  cd "$REPO_DIR"

  mkdir -p backend/data backend/extensions/installed

  echo ""
  success "Installation complete!"
  echo ""
  echo -e "  ${BOLD}To start NexusMind:${NC}"
  echo -e "    ${CYAN}./start-dev.sh${NC}"
  echo ""
  echo -e "  Or manually:"
  echo -e "    ${CYAN}cd backend && source venv/bin/activate && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload${NC}"
  echo -e "    ${CYAN}cd frontend && npm run dev${NC}"
  echo ""
  echo -e "  ${BOLD}URLs:${NC}"
  echo -e "    Frontend:  ${CYAN}http://localhost:3000${NC}"
  echo -e "    Backend:   ${CYAN}http://localhost:8000${NC}"
  echo -e "    API docs:  ${CYAN}http://localhost:8000/docs${NC}"
  echo ""

  read -rp "Start NexusMind now? [y/N]: " START_NOW
  if [[ "$START_NOW" =~ ^[Yy]$ ]]; then
    cd "$REPO_DIR"
    exec bash start-dev.sh
  fi

else
  # Docker Compose
  info "Building Docker images (this may take a few minutes)…"
  cd "$REPO_DIR"

  # Inject env into docker-compose via .env file at root
  cp backend/.env .env 2>/dev/null || true

  docker compose up --build -d 2>/dev/null || docker-compose up --build -d

  echo ""
  success "NexusMind is running via Docker!"
  echo ""
  echo -e "  ${BOLD}URLs:${NC}"
  echo -e "    Frontend:  ${CYAN}http://localhost:3000${NC}"
  echo -e "    Backend:   ${CYAN}http://localhost:8000${NC}"
  echo -e "    API docs:  ${CYAN}http://localhost:8000/docs${NC}"
  echo ""
  echo -e "  ${BOLD}Manage:${NC}"
  echo -e "    Stop:    ${CYAN}docker compose down${NC}"
  echo -e "    Logs:    ${CYAN}docker compose logs -f${NC}"
  echo -e "    Restart: ${CYAN}docker compose restart${NC}"
  echo ""
fi
